// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchResponse contains search results stored outside the database.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SearchResult represents search results from a single extension (plugin/theme/core).
type SearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ActiveInstalls int64                  `protobuf:"varint,4,opt,name=active_installs,json=activeInstalls,proto3" json:"active_installs,omitempty"`
	Matches        []*FileMatch           `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	TotalMatches   int32                  `protobuf:"varint,6,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	Downloaded     int64                  `protobuf:"varint,7,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SearchResult) GetActiveInstalls() int64 {
	if x != nil {
		return x.ActiveInstalls
	}
	return 0
}

func (x *SearchResult) GetMatches() []*FileMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *SearchResult) GetTotalMatches() int32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *SearchResult) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

// FileMatch represents all matches within a single file.
type FileMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Matches       []*Match               `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	AutoGenerated bool                   `protobuf:"varint,3,opt,name=auto_generated,json=autoGenerated,proto3" json:"auto_generated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMatch) Reset() {
	*x = FileMatch{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMatch) ProtoMessage() {}

func (x *FileMatch) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMatch.ProtoReflect.Descriptor instead.
func (*FileMatch) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *FileMatch) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMatch) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *FileMatch) GetAutoGenerated() bool {
	if x != nil {
		return x.AutoGenerated
	}
	return false
}

// Match represents a single line match within a file.
type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	LineNumber    int32                  `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Before        []string               `protobuf:"bytes,3,rep,name=before,proto3" json:"before,omitempty"`
	After         []string               `protobuf:"bytes,4,rep,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *Match) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Match) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *Match) GetBefore() []string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Match) GetAfter() []string {
	if x != nil {
		return x.After
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\"\x80\x01\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x03 \x03(\v2\x13.types.SearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05totalJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x05\x10\x06R\x04termR\x04repoR\vduration_ms\"\xea\x01\n" +
	"\fSearchResult\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12'\n" +
	"\x0factive_installs\x18\x04 \x01(\x03R\x0eactiveInstalls\x12*\n" +
	"\amatches\x18\x05 \x03(\v2\x10.types.FileMatchR\amatches\x12#\n" +
	"\rtotal_matches\x18\x06 \x01(\x05R\ftotalMatches\x12\x1e\n" +
	"\n" +
	"downloaded\x18\a \x01(\x03R\n" +
	"downloaded\"v\n" +
	"\tFileMatch\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12&\n" +
	"\amatches\x18\x02 \x03(\v2\f.types.MatchR\amatches\x12%\n" +
	"\x0eauto_generated\x18\x03 \x01(\bR\rautoGenerated\"j\n" +
	"\x05Match\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x05R\n" +
	"lineNumber\x12\x16\n" +
	"\x06before\x18\x03 \x03(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x03(\tR\x05afterB\x18Z\x16veloria/internal/typesb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_proto_goTypes = []any{
	(*SearchResponse)(nil), // 0: types.SearchResponse
	(*SearchResult)(nil),   // 1: types.SearchResult
	(*FileMatch)(nil),      // 2: types.FileMatch
	(*Match)(nil),          // 3: types.Match
}
var file_types_proto_depIdxs = []int32{
	1, // 0: types.SearchResponse.results:type_name -> types.SearchResult
	2, // 1: types.SearchResult.matches:type_name -> types.FileMatch
	3, // 2: types.FileMatch.matches:type_name -> types.Match
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
