package index

import (
	"bytes"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"regexp/syntax"
	"strings"
	"sync"
	"time"

	cindex "github.com/google/codesearch/index"
	cregexp "github.com/google/codesearch/regexp"
)

const (
	matchLimit               = 1000
	manifestFilename         = "metadata.gob"
	excludedFileJSONFilename = "excluded_files.json"
	filePeekSize             = 512
	reasonDotFile            = "Dot files are excluded."
	reasonInvalidMode        = "Invalid file mode."
	reasonNotText            = "Not a text file."
	reasonBinary             = "Binary files are excluded."
)

type Index struct {
	dir string
	idx *cindex.Index

	sync.RWMutex
}

type IndexOptions struct {
	ExcludeDotFiles    bool
	SpecialFiles       []string
	AutoGeneratedFiles []string
}

type SearchOptions struct {
	IgnoreCase        bool
	LiteralSearch     bool
	LinesOfContext    uint
	FileRegexp        string
	ExcludeFileRegexp string
	Offset            int
	Limit             int
	MaxResults        int
}

// CompiledSearch holds pre-compiled patterns for searching indexes.
// Create one via CompileSearch and reuse it across multiple Index.SearchCompiled calls
// to avoid redundant regex compilation.
//
// The rePool holds a sync.Pool of *cregexp.Regexp instances. Each goroutine borrows
// one from the pool for its search and returns it when done. This avoids recompiling
// the DFA regexp for every extension and — critically — lets the DFA state cache stay
// warm across extensions within the same worker, which makes subsequent matches
// nearly free (one table lookup per byte instead of recomputing DFA transitions).
type CompiledSearch struct {
	querySyntax    *syntax.Regexp
	pattern        string
	rePool         sync.Pool // pool of *cregexp.Regexp; not safe to copy CompiledSearch
	fre            *regexp.Regexp
	excludeFre     *regexp.Regexp
	maxResults     int
	linesOfContext int
	offset         int
	limit          int
}

// CompileSearch pre-compiles search patterns from the given term and options.
func CompileSearch(pat string, opt *SearchOptions) (*CompiledSearch, error) {
	if opt == nil {
		opt = &SearchOptions{}
	}

	patForRe := pat
	if opt.LiteralSearch {
		patForRe = regexp.QuoteMeta(pat)
	}

	fullPat := GetRegexpPattern(patForRe, opt.IgnoreCase)

	cre, err := cregexp.Compile(fullPat)
	if err != nil {
		return nil, err
	}

	cs := &CompiledSearch{
		querySyntax: cre.Syntax,
		pattern:     fullPat,
		rePool: sync.Pool{
			New: func() any {
				// Pattern was validated above; compilation cannot fail here.
				re, _ := cregexp.Compile(fullPat) //nolint:errcheck
				return re
			},
		},
		maxResults:     opt.MaxResults,
		linesOfContext: int(min(opt.LinesOfContext, uint(math.MaxInt))), // #nosec G115 -- clamped to MaxInt
		offset:         opt.Offset,
		limit:          opt.Limit,
	}

	if cs.maxResults <= 0 {
		cs.maxResults = matchLimit
	}

	if opt.FileRegexp != "" {
		cs.fre, err = regexp.Compile(opt.FileRegexp)
		if err != nil {
			return nil, err
		}
	}

	if opt.ExcludeFileRegexp != "" {
		cs.excludeFre, err = regexp.Compile(opt.ExcludeFileRegexp)
		if err != nil {
			return nil, err
		}
	}

	return cs, nil
}

type Match struct {
	Line       string   `json:"line"`
	LineNumber int      `json:"line_number"`
	Before     []string `json:"before,omitempty"`
	After      []string `json:"after,omitempty"`
}

type SearchResponse struct {
	Matches        []*FileMatch  `json:"matches"`
	FilesWithMatch int           `json:"files_with_match"`
	FilesOpened    int           `json:"-"`
	Duration       time.Duration `json:"-"`
	Revision       string        `json:"revision,omitempty"`
}

type FileMatch struct {
	Filename      string   `json:"filename"`
	Matches       []*Match `json:"matches"`
	AutoGenerated bool     `json:"auto_generated,omitempty"`
}

// Search searches the index for the given pattern and returns matching results.
func (i *Index) Search(pat string, opt *SearchOptions) (*SearchResponse, error) {
	cs, err := CompileSearch(pat, opt)
	if err != nil {
		return nil, err
	}
	return i.SearchCompiled(cs)
}

// SearchCompiled searches the index using pre-compiled search patterns.
// Use CompileSearch to create a CompiledSearch, then reuse it across multiple indexes.
func (i *Index) SearchCompiled(cs *CompiledSearch) (*SearchResponse, error) {
	startedAt := time.Now()

	// Borrow a DFA regexp from the pool. Each worker keeps its DFA state cache
	// warm across extensions, avoiding cold-start overhead on every call.
	re := cs.rePool.Get().(*cregexp.Regexp)
	defer cs.rePool.Put(re)

	i.RLock()
	defer i.RUnlock()

	files := i.idx.PostingQuery(cindex.RegexpQuery(cs.querySyntax))

	var (
		results          []*FileMatch
		filesOpened      int
		filesFound       int
		filesCollected   int
		matchesCollected int
	)

	for _, fileID := range files {
		if matchesCollected >= cs.maxResults {
			break
		}

		name := i.idx.Name(fileID).String()

		if cs.fre != nil && !cs.fre.MatchString(name) {
			continue
		}
		if cs.excludeFre != nil && cs.excludeFre.MatchString(name) {
			continue
		}

		filesOpened++

		matches, err := grepFile(name, re, cs.linesOfContext, cs.maxResults-matchesCollected)
		if err != nil {
			continue
		}

		if len(matches) > 0 {
			filesFound++

			if filesFound <= cs.offset {
				continue
			}
			if cs.limit > 0 && filesCollected >= cs.limit {
				continue
			}

			filesCollected++
			matchesCollected += len(matches)

			relName := name
			if idx := strings.Index(name, "/source/"); idx >= 0 {
				relName = name[idx+8:]
			}

			results = append(results, &FileMatch{
				Filename:      relName,
				Matches:       matches,
				AutoGenerated: false,
			})
		}
	}

	return &SearchResponse{
		Matches:        results,
		FilesWithMatch: filesFound,
		FilesOpened:    filesOpened,
		Duration:       time.Since(startedAt),
		Revision:       "",
	}, nil
}

var nlByte = []byte{'\n'}

// countNL counts the number of newline bytes in b.
func countNL(b []byte) int {
	n := 0
	for {
		i := bytes.IndexByte(b, '\n')
		if i < 0 {
			break
		}
		n++
		b = b[i+1:]
	}
	return n
}

// extractBeforeContext extracts up to n lines immediately before lineStart from buf.
func extractBeforeContext(buf []byte, lineStart int, n int) []string {
	if lineStart == 0 || n == 0 {
		return nil
	}

	// Collect lines backwards
	lines := make([]string, 0, n)
	end := lineStart
	if end > 0 && buf[end-1] == '\n' {
		end--
	}

	for i := 0; i < n && end > 0; i++ {
		start := 0
		if j := bytes.LastIndexByte(buf[:end], '\n'); j >= 0 {
			start = j + 1
		}
		lines = append(lines, string(buf[start:end]))
		end = start
		if end > 0 {
			end-- // skip \n before this line
		}
	}

	// Reverse to chronological order
	for i, j := 0, len(lines)-1; i < j; i, j = i+1, j-1 {
		lines[i], lines[j] = lines[j], lines[i]
	}
	return lines
}

// extractAfterContext extracts up to n lines immediately after lineEnd from buf.
func extractAfterContext(buf []byte, lineEnd int, n int) []string {
	if lineEnd >= len(buf) || n == 0 {
		return nil
	}

	lines := make([]string, 0, n)
	pos := lineEnd
	for i := 0; i < n && pos < len(buf); i++ {
		nlIdx := bytes.IndexByte(buf[pos:], '\n')
		if nlIdx < 0 {
			if pos < len(buf) {
				lines = append(lines, string(buf[pos:]))
			}
			break
		}
		lines = append(lines, string(buf[pos:pos+nlIdx]))
		pos = pos + nlIdx + 1
	}
	return lines
}

// grepFile searches a file for lines matching the regex and returns matches with context.
// Uses the codesearch DFA regexp engine on a whole-file buffer, jumping directly between
// matches without scanning non-matching lines.
func grepFile(filename string, re *cregexp.Regexp, contextLines int, maxMatches int) ([]*Match, error) {
	buf, err := os.ReadFile(filename) // #nosec G304 -- filename from internal index walk
	if err != nil {
		return nil, err
	}

	var (
		matches    []*Match
		chunkStart int
		end        = len(buf)
		beginText  = true
		lineno     = 1
	)

	for chunkStart < end && len(matches) < maxMatches {
		m := re.Match(buf[chunkStart:end], beginText, true) + chunkStart
		beginText = false
		if m < chunkStart {
			break
		}

		// Find line boundaries around the match
		lineStart := bytes.LastIndex(buf[chunkStart:m], nlByte) + 1 + chunkStart
		lineEnd := m + 1
		if lineEnd > end {
			lineEnd = end
		}

		// Track line numbers
		lineno += countNL(buf[chunkStart:lineStart])

		// Extract matched line without trailing newline/CR
		line := string(bytes.TrimRight(buf[lineStart:lineEnd], "\r\n"))

		match := &Match{
			Line:       line,
			LineNumber: lineno,
		}

		if contextLines > 0 {
			match.Before = extractBeforeContext(buf, lineStart, contextLines)
			match.After = extractAfterContext(buf, lineEnd, contextLines)
		}

		matches = append(matches, match)

		lineno++
		chunkStart = lineEnd
	}

	return matches, nil
}

// SourceDir returns the source directory path for this index.
func (i *Index) SourceDir() string {
	// The index dir is like /data/plugins/index/slug
	// The source dir is like /data/plugins/source/slug
	return filepath.Join(filepath.Dir(filepath.Dir(i.dir)), "source", filepath.Base(i.dir))
}

// Dir returns the directory path where this index is stored.
func (i *Index) Dir() string {
	return i.dir
}

// Close releases the resources held by this index.
// It nils out the internal pointer to allow garbage collection to release
// the mmap'd memory. Callers must not use the index after calling Close.
func (i *Index) Close() {
	i.Lock()
	defer i.Unlock()
	i.idx = nil
}
