package index

import (
	"bufio"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"regexp/syntax"
	"strings"
	"sync"
	"time"

	cindex "github.com/google/codesearch/index"
	cregexp "github.com/google/codesearch/regexp"
)

const (
	matchLimit               = 1000
	manifestFilename         = "metadata.gob"
	excludedFileJSONFilename = "excluded_files.json"
	filePeekSize             = 512
	reasonDotFile            = "Dot files are excluded."
	reasonInvalidMode        = "Invalid file mode."
	reasonNotText            = "Not a text file."
	reasonBinary             = "Binary files are excluded."
)

type Index struct {
	dir string
	idx *cindex.Index

	sync.RWMutex
}

type IndexOptions struct {
	ExcludeDotFiles    bool
	SpecialFiles       []string
	AutoGeneratedFiles []string
}

type SearchOptions struct {
	IgnoreCase        bool
	LiteralSearch     bool
	LinesOfContext    uint
	FileRegexp        string
	ExcludeFileRegexp string
	Offset            int
	Limit             int
	MaxResults        int
}

// CompiledSearch holds pre-compiled patterns for searching indexes.
// Create one via CompileSearch and reuse it across multiple Index.SearchCompiled calls
// to avoid redundant regex compilation.
type CompiledSearch struct {
	querySyntax    *syntax.Regexp
	re             *regexp.Regexp
	fre            *regexp.Regexp
	excludeFre     *regexp.Regexp
	maxResults     int
	linesOfContext int
	offset         int
	limit          int
}

// CompileSearch pre-compiles search patterns from the given term and options.
func CompileSearch(pat string, opt *SearchOptions) (*CompiledSearch, error) {
	if opt == nil {
		opt = &SearchOptions{}
	}

	patForRe := pat
	if opt.LiteralSearch {
		patForRe = regexp.QuoteMeta(pat)
	}

	fullPat := GetRegexpPattern(patForRe, opt.IgnoreCase)

	cre, err := cregexp.Compile(fullPat)
	if err != nil {
		return nil, err
	}

	re, err := regexp.Compile(fullPat)
	if err != nil {
		return nil, err
	}

	cs := &CompiledSearch{
		querySyntax:    cre.Syntax,
		re:             re,
		maxResults:     opt.MaxResults,
		linesOfContext: int(min(opt.LinesOfContext, uint(math.MaxInt))), // #nosec G115 -- clamped to MaxInt
		offset:         opt.Offset,
		limit:          opt.Limit,
	}

	if cs.maxResults <= 0 {
		cs.maxResults = matchLimit
	}

	if opt.FileRegexp != "" {
		cs.fre, err = regexp.Compile(opt.FileRegexp)
		if err != nil {
			return nil, err
		}
	}

	if opt.ExcludeFileRegexp != "" {
		cs.excludeFre, err = regexp.Compile(opt.ExcludeFileRegexp)
		if err != nil {
			return nil, err
		}
	}

	return cs, nil
}

type Match struct {
	Line       string   `json:"line"`
	LineNumber int      `json:"line_number"`
	Before     []string `json:"before,omitempty"`
	After      []string `json:"after,omitempty"`
}

type SearchResponse struct {
	Matches        []*FileMatch  `json:"matches"`
	FilesWithMatch int           `json:"files_with_match"`
	FilesOpened    int           `json:"-"`
	Duration       time.Duration `json:"-"`
	Revision       string        `json:"revision,omitempty"`
}

type FileMatch struct {
	Filename      string   `json:"filename"`
	Matches       []*Match `json:"matches"`
	AutoGenerated bool     `json:"auto_generated,omitempty"`
}

// Search searches the index for the given pattern and returns matching results.
func (i *Index) Search(pat string, opt *SearchOptions) (*SearchResponse, error) {
	cs, err := CompileSearch(pat, opt)
	if err != nil {
		return nil, err
	}
	return i.SearchCompiled(cs)
}

// SearchCompiled searches the index using pre-compiled search patterns.
// Use CompileSearch to create a CompiledSearch, then reuse it across multiple indexes.
func (i *Index) SearchCompiled(cs *CompiledSearch) (*SearchResponse, error) {
	startedAt := time.Now()

	i.RLock()
	defer i.RUnlock()

	files := i.idx.PostingQuery(cindex.RegexpQuery(cs.querySyntax))

	var (
		results          []*FileMatch
		filesOpened      int
		filesFound       int
		filesCollected   int
		matchesCollected int
	)

	for _, fileID := range files {
		if matchesCollected >= cs.maxResults {
			break
		}

		name := i.idx.Name(fileID).String()

		if cs.fre != nil && !cs.fre.MatchString(name) {
			continue
		}
		if cs.excludeFre != nil && cs.excludeFre.MatchString(name) {
			continue
		}

		filesOpened++

		matches, err := grepFile(name, cs.re, cs.linesOfContext, cs.maxResults-matchesCollected)
		if err != nil {
			continue
		}

		if len(matches) > 0 {
			filesFound++

			if filesFound <= cs.offset {
				continue
			}
			if cs.limit > 0 && filesCollected >= cs.limit {
				continue
			}

			filesCollected++
			matchesCollected += len(matches)

			relName := name
			if idx := strings.Index(name, "/source/"); idx >= 0 {
				relName = name[idx+8:]
			}

			results = append(results, &FileMatch{
				Filename:      relName,
				Matches:       matches,
				AutoGenerated: false,
			})
		}
	}

	return &SearchResponse{
		Matches:        results,
		FilesWithMatch: filesFound,
		FilesOpened:    filesOpened,
		Duration:       time.Since(startedAt),
		Revision:       "",
	}, nil
}

// grepFile searches a file for lines matching the regex and returns matches with context.
// Uses streaming I/O with a ring buffer for context lines to avoid loading entire files into memory.
func grepFile(filename string, re *regexp.Regexp, contextLines int, maxMatches int) (matches []*Match, err error) {
	f, err := os.Open(filename) // #nosec G304 -- filename from internal index walk
	if err != nil {
		return nil, err
	}
	defer func() {
		if cerr := f.Close(); err == nil && cerr != nil {
			err = cerr
		}
	}()

	scanner := bufio.NewScanner(f)
	lineNum := 0

	if contextLines <= 0 {
		// Fast path: no context lines needed, pure streaming
		for scanner.Scan() {
			lineNum++
			line := scanner.Text()
			if re.MatchString(line) {
				matches = append(matches, &Match{
					Line:       line,
					LineNumber: lineNum,
				})
				if len(matches) >= maxMatches {
					break
				}
			}
		}
	} else {
		// Context path: ring buffer for "before" lines
		ring := make([]string, contextLines)
		var pending []*Match

		for scanner.Scan() {
			line := scanner.Text()
			lineNum++

			// Fill "after" context for pending matches
			for i := len(pending) - 1; i >= 0; i-- {
				pending[i].After = append(pending[i].After, line)
				if len(pending[i].After) >= contextLines {
					pending[i] = pending[len(pending)-1]
					pending = pending[:len(pending)-1]
				}
			}

			if re.MatchString(line) {
				// Collect "before" context from ring buffer
				var before []string
				start := lineNum - contextLines
				if start < 1 {
					start = 1
				}
				for i := start; i < lineNum; i++ {
					before = append(before, ring[(i-1)%contextLines])
				}

				m := &Match{
					Line:       line,
					LineNumber: lineNum,
					Before:     before,
				}
				matches = append(matches, m)
				pending = append(pending, m)

				if len(matches) >= maxMatches {
					// Read remaining lines to fill "after" context
					for len(pending) > 0 && scanner.Scan() {
						afterLine := scanner.Text()
						for i := len(pending) - 1; i >= 0; i-- {
							pending[i].After = append(pending[i].After, afterLine)
							if len(pending[i].After) >= contextLines {
								pending[i] = pending[len(pending)-1]
								pending = pending[:len(pending)-1]
							}
						}
					}
					break
				}
			}

			// Store current line in ring buffer for future "before" context
			ring[(lineNum-1)%contextLines] = line
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return matches, nil
}

// SourceDir returns the source directory path for this index.
func (i *Index) SourceDir() string {
	// The index dir is like /data/plugins/index/slug
	// The source dir is like /data/plugins/source/slug
	return filepath.Join(filepath.Dir(filepath.Dir(i.dir)), "source", filepath.Base(i.dir))
}

// Dir returns the directory path where this index is stored.
func (i *Index) Dir() string {
	return i.dir
}

// Close releases the resources held by this index.
// It nils out the internal pointer to allow garbage collection to release
// the mmap'd memory. Callers must not use the index after calling Close.
func (i *Index) Close() {
	i.Lock()
	defer i.Unlock()
	i.idx = nil
}
