package model

import (
	"html"
	"math"
	"veloria/internal/index"
	"veloria/internal/manager"
	typespb "veloria/internal/types"
)

func SearchResponseToProto(resp *manager.SearchResponse) *typespb.SearchResponse {
	if resp == nil {
		return nil
	}

	out := &typespb.SearchResponse{
		Total: int32(min(resp.Total, math.MaxInt32)), // #nosec G115 -- clamped to MaxInt32
	}

	if len(resp.Results) == 0 {
		return out
	}

	out.Results = make([]*typespb.SearchResult, 0, len(resp.Results))
	for _, result := range resp.Results {
		if result == nil {
			continue
		}
		out.Results = append(out.Results, searchResultToProto(result))
	}

	return out
}

func SearchResponseFromProto(resp *typespb.SearchResponse) *manager.SearchResponse {
	if resp == nil {
		return nil
	}

	out := &manager.SearchResponse{
		Total: int(resp.GetTotal()),
	}

	results := resp.GetResults()
	if len(results) == 0 {
		return out
	}

	out.Results = make([]*manager.SearchResult, 0, len(results))
	for _, result := range results {
		if result == nil {
			continue
		}
		out.Results = append(out.Results, searchResultFromProto(result))
	}

	return out
}

func searchResultToProto(result *manager.SearchResult) *typespb.SearchResult {
	out := &typespb.SearchResult{
		Slug:           result.Slug,
		Name:           result.Name,
		Version:        result.Version,
		ActiveInstalls: int64(result.ActiveInstalls),
		Downloaded:     int64(result.Downloaded),
		TotalMatches:   int32(min(result.TotalMatches, math.MaxInt32)), // #nosec G115 -- clamped to MaxInt32
	}

	if len(result.Matches) == 0 {
		return out
	}

	out.Matches = make([]*typespb.FileMatch, 0, len(result.Matches))
	for _, match := range result.Matches {
		if match == nil {
			continue
		}
		out.Matches = append(out.Matches, fileMatchToProto(match))
	}

	return out
}

func searchResultFromProto(result *typespb.SearchResult) *manager.SearchResult {
	out := &manager.SearchResult{
		Slug:           result.GetSlug(),
		Name:           html.UnescapeString(result.GetName()),
		Version:        result.GetVersion(),
		ActiveInstalls: int(result.GetActiveInstalls()),
		Downloaded:     int(result.GetDownloaded()),
		TotalMatches:   int(result.GetTotalMatches()),
	}

	matches := result.GetMatches()
	if len(matches) == 0 {
		return out
	}

	out.Matches = make([]*index.FileMatch, 0, len(matches))
	for _, match := range matches {
		if match == nil {
			continue
		}
		out.Matches = append(out.Matches, fileMatchFromProto(match))
	}

	return out
}

func fileMatchToProto(match *index.FileMatch) *typespb.FileMatch {
	out := &typespb.FileMatch{
		Filename:      match.Filename,
		AutoGenerated: match.AutoGenerated,
	}

	if len(match.Matches) == 0 {
		return out
	}

	out.Matches = make([]*typespb.Match, 0, len(match.Matches))
	for _, lineMatch := range match.Matches {
		if lineMatch == nil {
			continue
		}
		out.Matches = append(out.Matches, matchToProto(lineMatch))
	}

	return out
}

func fileMatchFromProto(match *typespb.FileMatch) *index.FileMatch {
	out := &index.FileMatch{
		Filename:      match.GetFilename(),
		AutoGenerated: match.GetAutoGenerated(),
	}

	lineMatches := match.GetMatches()
	if len(lineMatches) == 0 {
		return out
	}

	out.Matches = make([]*index.Match, 0, len(lineMatches))
	for _, lineMatch := range lineMatches {
		if lineMatch == nil {
			continue
		}
		out.Matches = append(out.Matches, matchFromProto(lineMatch))
	}

	return out
}

func matchToProto(match *index.Match) *typespb.Match {
	return &typespb.Match{
		Line:       match.Line,
		LineNumber: int32(min(match.LineNumber, math.MaxInt32)), // #nosec G115 -- clamped to MaxInt32
		Before:     append([]string(nil), match.Before...),
		After:      append([]string(nil), match.After...),
	}
}

func matchFromProto(match *typespb.Match) *index.Match {
	return &index.Match{
		Line:       match.GetLine(),
		LineNumber: int(match.GetLineNumber()),
		Before:     append([]string(nil), match.GetBefore()...),
		After:      append([]string(nil), match.GetAfter()...),
	}
}
