// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd/veloria-converter/wpdirpb/search.proto

package wpdirpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Search_Status int32

const (
	Search_Queued    Search_Status = 0
	Search_Started   Search_Status = 1
	Search_Completed Search_Status = 2
)

// Enum value maps for Search_Status.
var (
	Search_Status_name = map[int32]string{
		0: "Queued",
		1: "Started",
		2: "Completed",
	}
	Search_Status_value = map[string]int32{
		"Queued":    0,
		"Started":   1,
		"Completed": 2,
	}
)

func (x Search_Status) Enum() *Search_Status {
	p := new(Search_Status)
	*p = x
	return p
}

func (x Search_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Search_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_veloria_converter_wpdirpb_search_proto_enumTypes[0].Descriptor()
}

func (Search_Status) Type() protoreflect.EnumType {
	return &file_cmd_veloria_converter_wpdirpb_search_proto_enumTypes[0]
}

func (x Search_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Search_Status.Descriptor instead.
func (Search_Status) EnumDescriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{0, 0}
}

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Started       string                 `protobuf:"bytes,4,opt,name=started,proto3" json:"started,omitempty"`
	Completed     string                 `protobuf:"bytes,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Progress      uint32                 `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Private       bool                   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	Status        Search_Status          `protobuf:"varint,8,opt,name=status,proto3,enum=wpdirpb.Search_Status" json:"status,omitempty"`
	Options       *Options               `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	Matches       uint32                 `protobuf:"varint,10,opt,name=matches,proto3" json:"matches,omitempty"`
	Revision      uint32                 `protobuf:"varint,11,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{0}
}

func (x *Search) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Search) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Search) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Search) GetStarted() string {
	if x != nil {
		return x.Started
	}
	return ""
}

func (x *Search) GetCompleted() string {
	if x != nil {
		return x.Completed
	}
	return ""
}

func (x *Search) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Search) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Search) GetStatus() Search_Status {
	if x != nil {
		return x.Status
	}
	return Search_Queued
}

func (x *Search) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Search) GetMatches() uint32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *Search) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IgnoreCase     bool                   `protobuf:"varint,1,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	LinesOfContext uint32                 `protobuf:"varint,2,opt,name=lines_of_context,json=linesOfContext,proto3" json:"lines_of_context,omitempty"`
	FileRegexp     string                 `protobuf:"bytes,3,opt,name=file_regexp,json=fileRegexp,proto3" json:"file_regexp,omitempty"`
	IgnoreComments bool                   `protobuf:"varint,4,opt,name=ignore_comments,json=ignoreComments,proto3" json:"ignore_comments,omitempty"`
	Offset         uint32                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *Options) GetLinesOfContext() uint32 {
	if x != nil {
		return x.LinesOfContext
	}
	return 0
}

func (x *Options) GetFileRegexp() string {
	if x != nil {
		return x.FileRegexp
	}
	return ""
}

func (x *Options) GetIgnoreComments() bool {
	if x != nil {
		return x.IgnoreComments
	}
	return false
}

func (x *Options) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Options) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          map[string]*Result     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{2}
}

func (x *Summary) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetList() map[string]*Result {
	if x != nil {
		return x.List
	}
	return nil
}

type Result struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Homepage       string                 `protobuf:"bytes,4,opt,name=homepage,proto3" json:"homepage,omitempty"`
	ActiveInstalls uint32                 `protobuf:"varint,5,opt,name=active_installs,json=activeInstalls,proto3" json:"active_installs,omitempty"`
	Matches        uint32                 `protobuf:"varint,6,opt,name=matches,proto3" json:"matches,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Result) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Result) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *Result) GetActiveInstalls() uint32 {
	if x != nil {
		return x.ActiveInstalls
	}
	return 0
}

func (x *Result) GetMatches() uint32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

type Matches struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Match               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matches) Reset() {
	*x = Matches{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matches) ProtoMessage() {}

func (x *Matches) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matches.ProtoReflect.Descriptor instead.
func (*Matches) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{4}
}

func (x *Matches) GetList() []*Match {
	if x != nil {
		return x.List
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	LineNum       uint32                 `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	LineText      string                 `protobuf:"bytes,4,opt,name=line_text,json=lineText,proto3" json:"line_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP(), []int{5}
}

func (x *Match) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Match) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Match) GetLineNum() uint32 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *Match) GetLineText() string {
	if x != nil {
		return x.LineText
	}
	return ""
}

var File_cmd_veloria_converter_wpdirpb_search_proto protoreflect.FileDescriptor

const file_cmd_veloria_converter_wpdirpb_search_proto_rawDesc = "" +
	"\n" +
	"*cmd/veloria-converter/wpdirpb/search.proto\x12\awpdirpb\"\xf4\x02\n" +
	"\x06Search\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x18\n" +
	"\astarted\x18\x04 \x01(\tR\astarted\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\tR\tcompleted\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\rR\bprogress\x12\x18\n" +
	"\aprivate\x18\a \x01(\bR\aprivate\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.wpdirpb.Search.StatusR\x06status\x12*\n" +
	"\aoptions\x18\t \x01(\v2\x10.wpdirpb.OptionsR\aoptions\x12\x18\n" +
	"\amatches\x18\n" +
	" \x01(\rR\amatches\x12\x1a\n" +
	"\brevision\x18\v \x01(\rR\brevision\"0\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06Queued\x10\x00\x12\v\n" +
	"\aStarted\x10\x01\x12\r\n" +
	"\tCompleted\x10\x02\"\xcc\x01\n" +
	"\aOptions\x12\x1f\n" +
	"\vignore_case\x18\x01 \x01(\bR\n" +
	"ignoreCase\x12(\n" +
	"\x10lines_of_context\x18\x02 \x01(\rR\x0elinesOfContext\x12\x1f\n" +
	"\vfile_regexp\x18\x03 \x01(\tR\n" +
	"fileRegexp\x12'\n" +
	"\x0fignore_comments\x18\x04 \x01(\bR\x0eignoreComments\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\"\x99\x01\n" +
	"\aSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12.\n" +
	"\x04list\x18\x02 \x03(\v2\x1a.wpdirpb.Summary.ListEntryR\x04list\x1aH\n" +
	"\tListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.wpdirpb.ResultR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x06Result\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhomepage\x18\x04 \x01(\tR\bhomepage\x12'\n" +
	"\x0factive_installs\x18\x05 \x01(\rR\x0eactiveInstalls\x12\x18\n" +
	"\amatches\x18\x06 \x01(\rR\amatches\"-\n" +
	"\aMatches\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.wpdirpb.MatchR\x04list\"g\n" +
	"\x05Match\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\rR\alineNum\x12\x1b\n" +
	"\tline_text\x18\x04 \x01(\tR\blineTextB'Z%veloria/cmd/veloria-converter/wpdirpbb\x06proto3"

var (
	file_cmd_veloria_converter_wpdirpb_search_proto_rawDescOnce sync.Once
	file_cmd_veloria_converter_wpdirpb_search_proto_rawDescData []byte
)

func file_cmd_veloria_converter_wpdirpb_search_proto_rawDescGZIP() []byte {
	file_cmd_veloria_converter_wpdirpb_search_proto_rawDescOnce.Do(func() {
		file_cmd_veloria_converter_wpdirpb_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_veloria_converter_wpdirpb_search_proto_rawDesc), len(file_cmd_veloria_converter_wpdirpb_search_proto_rawDesc)))
	})
	return file_cmd_veloria_converter_wpdirpb_search_proto_rawDescData
}

var file_cmd_veloria_converter_wpdirpb_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cmd_veloria_converter_wpdirpb_search_proto_goTypes = []any{
	(Search_Status)(0), // 0: wpdirpb.Search.Status
	(*Search)(nil),     // 1: wpdirpb.Search
	(*Options)(nil),    // 2: wpdirpb.Options
	(*Summary)(nil),    // 3: wpdirpb.Summary
	(*Result)(nil),     // 4: wpdirpb.Result
	(*Matches)(nil),    // 5: wpdirpb.Matches
	(*Match)(nil),      // 6: wpdirpb.Match
	nil,                // 7: wpdirpb.Summary.ListEntry
}
var file_cmd_veloria_converter_wpdirpb_search_proto_depIdxs = []int32{
	0, // 0: wpdirpb.Search.status:type_name -> wpdirpb.Search.Status
	2, // 1: wpdirpb.Search.options:type_name -> wpdirpb.Options
	7, // 2: wpdirpb.Summary.list:type_name -> wpdirpb.Summary.ListEntry
	6, // 3: wpdirpb.Matches.list:type_name -> wpdirpb.Match
	4, // 4: wpdirpb.Summary.ListEntry.value:type_name -> wpdirpb.Result
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cmd_veloria_converter_wpdirpb_search_proto_init() }
func file_cmd_veloria_converter_wpdirpb_search_proto_init() {
	if File_cmd_veloria_converter_wpdirpb_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_veloria_converter_wpdirpb_search_proto_rawDesc), len(file_cmd_veloria_converter_wpdirpb_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_veloria_converter_wpdirpb_search_proto_goTypes,
		DependencyIndexes: file_cmd_veloria_converter_wpdirpb_search_proto_depIdxs,
		EnumInfos:         file_cmd_veloria_converter_wpdirpb_search_proto_enumTypes,
		MessageInfos:      file_cmd_veloria_converter_wpdirpb_search_proto_msgTypes,
	}.Build()
	File_cmd_veloria_converter_wpdirpb_search_proto = out.File
	file_cmd_veloria_converter_wpdirpb_search_proto_goTypes = nil
	file_cmd_veloria_converter_wpdirpb_search_proto_depIdxs = nil
}
