name: Go Lint, Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.github/**', 'docs/**', 'README.md' ]
  pull_request:
    paths-ignore: [ '.github/**', 'docs/**', 'README.md' ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: jsonv2,greenteagc
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.26.0'
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Generate assets
        run: go generate ./assets

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v9
      #   with:
      #     version: v2.6

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude-generated -exclude-dir=internal/codesearch ./...
